using System;
using System.Collections.Generic;
using System.Linq;
using hotel_management_final_project.Models;
using hotel_management_final_project.Repository;
namespace hotel_management_final_project
{
    public class Database
    {
        public static List<Room> Rooms = new List<Room>();
        public static List<Room> ReservedRooms = new List<Room>();
        public static List<Admin> Admins = new List<Admin>();
        public static List<Booking> Bookings = new List<Booking>();
        public static List<Customer> Customers = new List<Customer>();
        CustomerService customerService = new CustomerService();
        RoomService roomService = new RoomService();
        BookingService bookingService = new BookingService();


        public static void DefaultRooms()
        {
            Rooms.Add(new Room() { Id = 101, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 102, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 103, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 104, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 105, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 106, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 107, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 108, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 109, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 110, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 111, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 112, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 113, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 114, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 115, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 116, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 117, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 118, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 119, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 120, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 121, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 122, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 123, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 124, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 125, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 126, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 127, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 128, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 129, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 130, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 131, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 132, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 133, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 134, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 135, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 136, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 137, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 138, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 139, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 140, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 201, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 202, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 203, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 204, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 205, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 206, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 207, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 208, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 209, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 210, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 211, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 212, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 213, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 214, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 215, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 216, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 217, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 218, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 219, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 220, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 221, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 222, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 223, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 224, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 225, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 226, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 227, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 228, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 229, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 230, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 231, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 232, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 233, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 234, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 235, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 236, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 237, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 238, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 239, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 240, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 301, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 302, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 303, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 304, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 305, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 306, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 307, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 308, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 309, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 310, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 311, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 312, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 313, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 314, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 315, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 316, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 317, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 318, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 319, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 320, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 321, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 322, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 323, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 324, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 325, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 326, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 327, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 328, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 329, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 330, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 331, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 332, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 333, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 334, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 335, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 336, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 337, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 338, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 339, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 340, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 401, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 402, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 403, Type = "Single", Price = 120, Availability = true });
            Rooms.Add(new Room() { Id = 404, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 405, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 406, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 407, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 408, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 409, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 410, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 411, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 412, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 413, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 414, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 415, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 416, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 417, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 418, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 419, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 420, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 421, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 422, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 423, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 424, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 425, Type = "Double", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 426, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 427, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 428, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 429, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 430, Type = "Twin", Price = 150, Availability = true });
            Rooms.Add(new Room() { Id = 431, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 432, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 433, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 434, Type = "Deluxe", Price = 250, Availability = true });
            Rooms.Add(new Room() { Id = 435, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 436, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 437, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 438, Type = "Deluxe King", Price = 350, Availability = true });
            Rooms.Add(new Room() { Id = 439, Type = "Executive", Price = 550, Availability = true });
            Rooms.Add(new Room() { Id = 440, Type = "Executive", Price = 550, Availability = true });
        }
        public static void DefaultUsers()
        {
            Admins.Add(new Admin() { Id = 1, Name = "Mike", Surname = "Jackson", Email = "mike.jackson@gmail.com", Password = "mike123", Username = "mike.jackson" });
            Admins.Add(new Admin() { Id = 2, Name = "Richard", Surname = "Thompson", Email = "richard.thompson@gmail.com", Password = "richard123", Username = "richard.thompson" });
            Admins.Add(new Admin() { Id = 3, Name = "James", Surname = "Nickson", Email = "james.nickson@gmail.com", Password = "james123", Username = "james.nickson" });
        }


    }
}
